from datetime import datetime
import time

import streamlit as st
from langchain_google_genai import GoogleGenerativeAI
from dotenv import load_dotenv
import os, sys, json
from fpdf import FPDF
from streamlit_extras.switch_page_button import switch_page
from PIL import Image


# Home Page Content
def app():
    st.markdown("<h1 style='text-align: center;'>🚀 Welcome to SalesTrek</h1>", unsafe_allow_html=True)
    # You can add your about section content here
    st.write("""
    SalesTrek is your AI-powered sales and marketing assistant designed to help you succeed in the competitive world of sales. Whether you're an experienced sales professional or new to the field, SalesTrek has the tools and guidance you need to achieve your goals.
    """)
    st.markdown("---")
    st.markdown("### ✨Features")
    st.markdown*("---")
    #markdown table
    st.markdown("""
    | Feature | Description |
    | --- | --- |
    | AI Sales Coach | Get expert advice and guidance on sales strategies, objection handling, and more. |
    | Sales Script Generator | Generate custom sales scripts and email templates tailored to your needs. |
    | Email Generator | Create engaging and effective email templates for your sales campaigns. |
    | Summarizer | Summarize long texts or articles quickly and efficiently. |
    | Image Scan | Analyze images and extract text for further processing. |
    | Settings | Customize your SalesTrek experience with personalized settings. |
    """)
    st.markdown("### 🤔 How to Use")
    #Step by step instructions
    st.markdown("""
    1. **Select a Feature**: Choose a feature from the sidebar menu.
    2. **Input Data**: Enter the required data or content for the selected feature.
    3. **Click on the Button**: Click on the corresponding button to run the feature.
    4. **View Results**: Review the results or output generated by the feature.
    """)
    
    st.markdown("### 📅 Upcoming Features")
    st.markdown("""
                - **Sales Forecasting**: Predict future sales trends and outcomes based on historical data.
                - **Lead Scoring**: Identify and prioritize high-quality leads for better conversion rates.
                - **CRM Integration**: Connect SalesTrek with your CRM system for seamless data management.
                - **Sales Analytics**: Analyze sales performance and metrics to optimize your strategies.
                - **Voice Assistant**: Interact with SalesTrek using voice commands for hands-free operation.
                """)
                
app()